name: Build and Deploy

on:
  push:
    branches: [main]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    env:
      REPO: ${{ github.repository }}
      TAG: latest

    steps:
      - uses: actions/checkout@v4
      
      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: docker compose -f docker-compose.prod.yml build

      - name: Push images
        run: docker compose -f docker-compose.prod.yml push

  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ssh and redeploy
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         port: ${{ secrets.SSH_PORT }}
  #         script: |
  #           docker pull ghcr.io/rinorhasani/fullcircletesting:latest
  #           docker stop frontend || true
  #           docker rm frontend ||  true 
  #           docker run -d \
  #             --name frontend \
  #             -p 80:3000 \
  #             ghcr.io/rinorhasani/fullcircletesting:latest
              
          
      
        
        
      
    
            
            
          
          
